spring:
  datasource:
    # ?????PostgreSQL??????????
    url: jdbc:postgresql://localhost:5432/pokemondb
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  flyway:
    # ?????????? migration ?????
    enabled: true
    locations: classpath:db/migration

mybatis:
  configuration:
    # DB?????(snake_case)?Java???????(camelCase)?????
    # ?: pokemon_name -> pokemonName
    map-underscore-to-camel-case: true
  # ????XML?SQL??????????????????
  # mapper-locations: classpath:mapper/*.xml

# SpringDoc (Swagger) ???
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    # ?????API???
    display-tags-as-default: true